### ISSUE TITLE
how to store DB?

### ISSUE THREAD

**Issue by DaniilBezliudnov** [DaniilBezliudnov/HobbyClub#2]
1. Хостинг?
2. гитхаб + локальные копии.
3. независимые локальные копии.
4. Active Directory + VPN (общая папка)
5. Azure????

**Comment by katerynaZh** [comment]
1 - если хостинг, то какой?) 
Наличие локальных копий  нравится тем, что в случае если кто-то сломает БД (я могу), у остальных она будет целая и заменить поломанную копию не составит большого труда), хотя могу и ошибаться)
5 - azure, никогда не работала и мне интересно узнать что это и как его едят)

**Comment by DaniilBezliudnov** [comment]
http://azure.microsoft.com/ru-ru/pricing/
Учитывая что если зарегаться дают 10к рублей (а сервис бд стои 249,50) - то мы можем в принципе юзать и Azure

**Comment by kristinafdrv** [comment]
Может быть, есть возможность как-то хостить БД в епаме (не Active Directory)? Мне интересно узнать, что делают на продакшне в таких случаях.
Чем мне не нравится вариант с Active Directory: файлик бд 1 лежит где-то, а каждый пытается со своей машины, своей СУБД достучаться к нему. Не будет ли просто блокировки БД первым, кто к ней достучался своим MS SQL сервером?

**Comment by katerynaZh** [comment]
"Мне интересно узнать, что делают на продакшне в таких случаях" - мне тоже)
Там где  работала, насколько я помню была одна БД, а у остальных были ее
рабочие копии.

Может просто расшарить файлик на всех, но каждый что б работал с копией
этого файла?

12 марта 2015 г., 21:51 пользователь Khrystyna Fedorova <
notifications@github.com> написал:

**Comment by katerynaZh** [comment]
давайте попробуем azure, нам на курсах говорили, что его в программу курсов добавили, значит так или иначе нам нужно будет знать как с ним работать

**Comment by kristinafdrv** [comment]
1. Хороший аргумент в пользу azure
2. "Наличие локальных копий нравится тем, что в случае если кто-то сломает БД (я могу), у остальных она будет целая и заменить поломанную копию не составит большого труда), хотя могу и ошибаться)" - ну тут, наверное, можно будет обойтись бек-апами.

**Comment by DaniilBezliudnov** [comment]
Имхо пробуем Azure (ща я займусь), если выйдет - ок,
не выйдет - юзаем бд на каждом компе (каждый тестит как хочет) и кто-то делает нормальною БД для релиз версии

**Comment by DaniilBezliudnov** [comment]
Создал в Azure БД - работает вполне замечательно - юзать можно

**Comment by katerynaZh** [comment]
ура!)

12 марта 2015 г., 23:09 пользователь DaniilBezliudnov <
notifications@github.com> написал:

**Comment by DaniilBezliudnov** [comment]
Azure
