### ISSUE TITLE
'Comment' db entity

### ISSUE THREAD

**Issue by DaniilBezliudnov** [DaniilBezliudnov/HobbyClub#20]
Fields, foreign keys?

**Comment by kristinafdrv** [comment]
ID
  Text
Foreign keys:
1.  UserID
2.  EventID

**Comment by DaniilBezliudnov** [comment]
+Date

**Comment by alexakryvenko** [comment]
Если не будем делать +/- к коментам (как лайки, поднять выше/опустить), то хватит этого.

**Comment by DaniilBezliudnov** [comment]
ID
Text
Date

Foreign keys:
    UserID
    EventID
