### ISSUE TITLE
Create user story

### ISSUE THREAD

**Issue by DaniilBezliudnov** [DaniilBezliudnov/HobbyClub#30]
List of "I want", "User want" "When i open page i want to see..." and so on.

**Comment by alexakryvenko** [comment]
https://docs.google.com/document/d/1D1e0DxZWDmT_pDg3Y_ngoO6RKsGagROY5U3KLQn3WZw/edit#heading=h.6i1uwo2xbeu0

**Comment by DaniilBezliudnov** [comment]
done
