### ISSUE TITLE
How to organize chat? How to save chat history?

### ISSUE THREAD

**Issue by DaniilBezliudnov** [DaniilBezliudnov/HobbyClub#6]
1. Push notification
2. Ask server whole time.
3. Web Service
4. Комментарии? Хватит ли их?

**Comment by katerynaZh** [comment]
Предлагаю сохранять историю чата в БД. Тогда надо будет в базу данных добавить две таблички: первая табличка Messagess: Id, groupId,  time, message и PersonsChatsMessages: idPerson, idMessage. У одной группы - один чат.

Когда человек заходит в группу, мы подгружаем к примеру последние 20 сообщений из БД, сохраняем их например в какую-то переменную messages в виде массива, которые тут же отображаются на вьюшке, и после этого опрашиваем сервер на наличие новых сообщений с определенным интервалом. Если сообщения новые есть, мы добавляем их в уже существующий массив messages и наша вьюшка перерисовывается. На angular это вроде не сложно будет сделать.

**Comment by DaniilBezliudnov** [comment]
"опрашиваем сервер на наличие новых сообщений с определенным интервалом" - это ОЧЕНЬ плохой способ, т.к. ты постоянно занимаеш канал. А если у нас много юзеров? Все постоянно шлют "а есть сообщения?", "а сейчас?", "а может уже есть?" и таких сообщений слишком много может быть.
В идеале да - хранить в бд и каким-то образом Push`ить новые сообщения всем юзерам в группе.

**Comment by katerynaZh** [comment]
не подумала над этим... а как тогда сделать хорошо?)

12 марта 2015 г., 21:17 пользователь DaniilBezliudnov <
notifications@github.com> написал:

**Comment by kristinafdrv** [comment]
Как насчет использования готовых библиотек для создания чата?
Например, http://signalr.net/

**Comment by DaniilBezliudnov** [comment]
О, кстати, когда-то слышал что signal - крутая (полезная) штука - предлагаю попробовать (и обучение и вроде бы подходит)

**Comment by katerynaZh** [comment]
я не против

12 марта 2015 г., 22:16 пользователь Khrystyna Fedorova <
notifications@github.com> написал:

**Comment by alexakryvenko** [comment]
Я установила себе пример этой штуковины (Install-Package Microsoft.AspNet.SignalR.Sample). Через хром у меня не работают кнопки вообще, а в експлорере вываливается ексепшн в джаваскрипте)) Попробуйте, может у вас норм будет.

**Comment by kristinafdrv** [comment]
Когда я установила себе пример, то ничего у меня не вышло. Потом я нашла туториал:
http://www.asp.net/signalr/overview/getting-started/tutorial-getting-started-with-signalr-and-mvc
Работает все как надо. Насколько я поняла, в данном туториале история сообщений нигде не хранится. Просто рассылка всем сообщения и аппенд в html.
По ссылке ниже есть информация, как с помощью SignalR получать данные из БД в реальном времени без обновления страницы:
http://venkatbaggu.com/signalr-database-update-notifications-asp-net-mvc-usiing-sql-dependency/
Эксепшн в джаваскрипте и не работать кнопки могли из-за того, что ты могла ссылаться на неправильную версию скрипта jquery.signalR-X.X.X.min.js.
Когда ставишь SignalR себе через NuGet происходит один баг. По ссылке более подробно о нем и его решении:
http://stackoverflow.com/questions/12027543/visual-studio-2012-web-api-project-wont-run-cant-find-newtonsoft-json
ИМХО, можно спокойно использовать SignalR. Как хранить историю чата для SignalR не важно.

**Comment by DaniilBezliudnov** [comment]
Закрываю эту проблему с решением юзать signalR и создаю новую на реализацию
