### ISSUE TITLE
Where to save comments?

### ISSUE THREAD

**Issue by DaniilBezliudnov** [DaniilBezliudnov/HobbyClub#7]
1. Disqus 
2. Our DB

**Comment by kristinafdrv** [comment]
Disqus можно использовать только, подключая его к сайту, который где-то уже хостится. Иначе оно даже зарегаться не дает на сайте.

**Comment by kristinafdrv** [comment]
Disqus хранит все комментарии у себя на серверах. Подключается к страничке довольно просто, в 15 строчек скопипащенного практически полностью с официального сайта кода (кроме значения 1 переменной). Вроде он аяксе, т.к. страничка при появлении новых комментариев не перезагружается.
Остается вопрос, как сделать так, чтоб Disqus автоматически подтягивал данные юзера при создании ним комментария? (Чтоб уже авторизованный пользователь не вводил каждый раз свою почту и ник в форме комментария)

**Comment by kristinafdrv** [comment]
Написала в саппорт в Disqus, попросила включить SSO для своего аккаунта.
Тут есть информация, как это - "чтоб Disqus автоматически подтягивал данные юзера при создании ним комментария? " - сделать
https://github.com/disqus/DISQUS-API-Recipes/blob/b019c40d2b3f91d7497e700f6b81882d7c1a730e/sso/cs/DisqusSSO.cs
https://help.disqus.com/customer/portal/articles/684744

**Comment by DaniilBezliudnov** [comment]
Лучше напиши какие мы получим + при хранении коментариев в Дискусе, а не в нашей базе.

**Comment by kristinafdrv** [comment]
1. Плюсы:
   - о комментариях вообще не надо думать, скопипастил 15 строчек кода - все работает.
   - БД не разрастается быстро, т.к. таблички с комментами в ней не будет 
2.  Минусы:
   - если нет интернета, то комментарии не подгружаются (плохо на момент разработки)
   - скопипастил 15 строчек кода - все работает. Т.к. у нас учебный проект, все-таки имеет смысл делать комментарии руками, с аяксом и пр.
   - все комментарии видны пользователям Disqus

**Comment by DaniilBezliudnov** [comment]
Our DB
